# Generated by Django 4.2.16 on 2026-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Le Média', max_length=120, verbose_name='Nom du site')),
                ('slogan', models.CharField(default="L'info qui compte", max_length=200, verbose_name='Slogan')),
                ('site_description', models.TextField(blank=True, default='Plateforme d’information, d’analyses et de reportages.', verbose_name='Description du site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo du site')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Lien Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Lien X / Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Lien Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Lien YouTube')),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
