# Generated by Django 4.2.16 on 2026-09-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='Texte alternatif')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
            options={
                'verbose_name': 'Image d’article',
                'verbose_name_plural': 'Images d’article',
                'ordering': ['position', 'id'],
            },
        ),
    ]
